stages:
  - test

default:
  interruptible: true
  timeout: 30m
  tags:
    - sh-grun
  before_script:
    - source env.sh
    - module list

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

variables:
  GIT_DEPTH: "1"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1

redhat-no-license:
  stage: test
  script:
    - ./tests/redhat_smoke.sh
